const Actions = {
	UPDATE_CONDITION: 'UPDATE_CONDITION',
	UPDATE_BOOK_RESULT: 'UPDATE_BOOK_RESULT',
	UPDATE_KEYWORD_HISTORY_RESULT: 'UPDATE_KEYWORD_HISTORY_RESULT',
	UPDATE_HOT_KEYWORD_RESULT: 'UPDATE_HOT_KEYWORD_RESULT'
};

export default Actions;